### ISSUE TITLE
Heading font in Settings App

### ISSUE THREAD

**Issue by abstergo17** [Evolution-X/frameworks_base#31]
Headline font in the Settings App is 'Google Sans Text' instead of Google Sans unlike in stock Pixel ROM.

Settings App from Evolution X AOSP Version -
![Screenshot_20240816-082517_Settings](https://github.com/user-attachments/assets/d703d5b5-6935-4ccd-8fb2-3bf703de90cf)

Current Settings App from Evolution X Lineage based version -
![Screenshot_20240816-082454_Pixel Launcher](https://github.com/user-attachments/assets/6d880a01-6f0c-4d96-b836-bb501822ff15)

**Comment by DarkAngelGR** [comment]
I'm gonna touch you

**Comment by joeyhuab** [comment]
https://github.com/Evolution-X/vendor_pixel-framework/blob/0cea612ba1a4926dc80e5e71593f09510a8b9be0/SettingsGoogle/res/values/strings.xml#L542

FYI
