### ISSUE TITLE
Make The Pure Black Dark Mode Consistent

### ISSUE THREAD

**Issue by YouSummoner** [Evolution-X/frameworks_base#32]
In some elements of the ROM, turning on the Pure Black mode has no effect, suck as the notification area background(not the qs panel background), the background of the notification itself, and the background of the audio output dailog. These instead end up looking Gray.
This makes the ROM look inconsistent and jarring in daily use, considering the user has specifically chosen to use the Pure Black mode instead of the normal dark mode.
Please make it look something like the samples I've attached below
![Screenshot_20240820-021717_Kiwi Browser](https://github.com/user-attachments/assets/471e55ef-f18c-41f0-bfc7-7a1c4ea64a21)
![Screenshot_20240820-022646_Quetta](https://github.com/user-attachments/assets/871a44a5-6d8a-41af-a79f-e058ca70f464)

**Comment by joeyhuab** [comment]
https://github.com/Evolution-X/vendor_extras/tree/udc/themes/system/BlackTheme

Better check the code and adapt it yourself and make a PR.
